#Server configuration
server:
  port: 9000

#Logging configuration
logging:
  level:
    com.nayanzin: debug
  file:
    path: logs
    name: monitoring.log
    max-size: 10MB

#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  #Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5433/dev_db
    username: dev_user
    password: dev_password
  h2:
    console:
      enabled: true
      path: /db-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate